### ISSUE TITLE
Related Pages ne fonctionne plus après mise à jour Dotclear 2.27, puis 2.27.1

### ISSUE THREAD

**Issue by geba38490** [Philippe-dev/related#11]
Bonjour,

Depuis longtemps, j'utilise le plugin Related Pages pour une page Table des Matières (Liste des billets par catégorie) de mon site construite avec le widget mrvbToC de Mirovinben. Depuis la mise à jour 2.27 puis 2.27.1 de Dotclear, Related Pages ne fonctionne plus. En appelant la page Table des Matières, j'obtiens une erreur Dotclear : 585 : Unable to find template Something went wrong while loading template file for your blog.

Merci par avance. Cordialement

**Comment by nikrou** [comment]
Release 1.9.0 works with dotclear 2.27
