### ISSUE TITLE
Related page ne fonctionne pas sous dotclear 2.28 et +

### ISSUE THREAD

**Issue by C-AnCa2** [Philippe-dev/related#13]
Bonjour

------ Pour «  related page » erreur lorsque l’on va sur la  page de configuration  et enregistrement >> erreur

Dotclear  503 : Site temporarily unavailable  Call to a member function redirect() on null

------ Et l’ouverture et sur la  Page principale du plugin>>>> erreur

Fatal error: Type of Dotclear\Plugin\related\ActionsRelatedPages::$use_render must be bool (as in class Dotclear\Core\Backend\Action\Actions) in *******www/AA_CIQ_AV/plugins/related/src/ActionsRelatedPages.php on line 23

------ Et en plus il y a erreur sur le site si l’on met le Widget page related  il y a l’erreur

571 : Template handling error  Something went wrong while loading template file for your blog.

Merci par avance pour la mise à jour

**Comment by nikrou** [comment]
Corrigé dans la version 2.0.1

**Comment by C-AnCa2** [comment]
Bonjour Nikrou,
Merci pour votre réponse. Vous indiquez que la version 2.0.1 a été corrigée. 
Je l'ai installée sur un Dotclear 28.1 natif, c'est-à-dire avec des plugins officiels plus Related, mais il ne fonctionne toujours pas. 
Vous seriez-t-il  possible, svp,  de le mettre à jour pour la dernière version de Dotclear ? 
En effet, Related Pages est crucial pour le fonctionnement de notre CIQ, toutes nos pages de contact l'utilisent. 
Merci pour votre retour.
Antoine
