### ISSUE TITLE
related pages version 2.0.1  pour dotclear 2.28.1

### ISSUE THREAD

**Issue by C-AnCa2** [Philippe-dev/related#14]
Bonjour 

Désolé d'insisté mais comme je vous l'avez dit ce plugin et majeur pour notre blog:
Précision dur les erreusr sur un blog natif .

Lorsque sur le menu blog on clique sur related pages on l’erreur 

503 : Site temporarily unavailable
count(): Argument #1 ($value) must be of type Countable|array, null given

et lorsque l'on veut configurer

Dotclear
503 : Site temporarily unavailable
Dotclear\Helper\Html\Form\Input::__construct(): Argument #2 ($type) must be of type string, null given, called in /home/dprlajd/www/AA_CIQ_AV/plugins/related/src/Config.php on line 126

Merci pour votre patience.

Cordialement.
Antoine

**Comment by Philippe-dev** [comment]
Il y a une release 2.0.2 sur ce dépôt

**Comment by nikrou** [comment]
> Désolé d'insisté mais comme je vous l'avez dit ce plugin et majeur pour notre blog:

Pour les urgences, mon mail est disponible... En retour, je vous ferai un devis.

**Comment by C-AnCa2** [comment]
Je ne comprends pas. J'utilise Dotclear depuis des années et j'ai toujours effectué les mises à jour jusqu'à la version 2.27.3. De plus, vous aviez mis à jour le plugin et l'aviez intégré à Dotclear.

Je ne suis donc pas un novice en matière de mise à jour. Pour éviter tout problème, je pars d'une installation Dotclear native et je vérifie l'ensemble des plugins que j'utilise afin de ne pas perturber mon blog principal.

Je ne comprends pas pourquoi les dernières mises à jour, y compris la version 2.02, ne fonctionnent pas. 
Pourquoi ne pas les intégrer à Dotclear pour qu'ils soient testés par des utilisateurs plus expérimentés que moi ?

Ce n'est pas une urgence pour l'instant, car comme je vous l'ai déjà dit, mon blog principal n'est pas impacté. Je suis prudent. Un chat échaudé craint l'eau froide.

Merci encore.

**Comment by geba3894** [comment]
Bonjour,

J'ai déjà posté sur le forum, mais recopie mon problème ici.

Sur mon installation Dotclear 2.32.1, je crée un 3ème blog. Les mêmes thèmes et les mêmes plugins sont partagés depuis un dossier all-blogs. La version 2.02 du plugin Pages connexes (related) installée, fonctionne pour 2 blogs. Pour le 3ème, l'option Configurer le plugin produit une erreur 503 en validant après avoir coché la case "Activer le plugin".

`Dotclear
503 : Site temporarily unavailable
Dotclear\Helper\Html\Form\Input::__construct(): Argument #2 ($type) must be of type string, null given, called in /home/sentiern/www/all-blogs/plugins/related/src/Config.php on line 126
`

La ligne 126 de Config.php :

`(new Input('related_files_path', $settings->files_path))->size(80)->max(255)->value($settings->files_path),`

L'option Page principale du plugin affiche l'erreur :

`Dotclear
503 : Site temporarily unavailable
count(): Argument #1 ($value) must be of type Countable|array, null given`

Quel pourrait-être le problème de ce 3ème blog ? Grand merci par avance.
